#+TITLE:     Adapted html themes for org exports
#+AUTHOR:    FXR Insights
#+EMAIL:     support at fxr-insights dot com
#+OPTIONS:   H:4 toc:t num:2

#+PROPERTY:  header-args :padline no
#+SETUPFILE: ./org/theme-readtheorg.setup

This is a modified version of the amazing [[https://github.com/fniessen/org-html-themes][org-html-themes]] by Fabrice
Niessen. The colour schemes of the themes have been modified to more align with
the FXR Insights brand colours.

* License

Copyright (C) 2022 FXR Insights
Author: FXR Insights

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program.  If not, see http://www.gnu.org/licenses/.
